openapi: 3.1.0
info:
  title: Scenario Generation API - Extended
  description: |
    Extended API endpoints for feature 005: Complete Demo Scenario Pipeline.
    Adds vehicle lookup and policy indexing capabilities.
  version: 1.1.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /vehicles/{vin}:
    get:
      summary: Get vehicle by VIN
      description: Retrieve vehicle information by VIN number
      operationId: getVehicleByVin
      tags:
        - vehicles
      parameters:
        - name: vin
          in: path
          required: true
          schema:
            type: string
            minLength: 17
            maxLength: 17
          description: Vehicle Identification Number
      responses:
        '200':
          description: Vehicle found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleRecord'
        '404':
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /vehicles/by-policy/{policy_number}:
    get:
      summary: Get vehicle by policy number
      description: Retrieve vehicle information associated with a policy
      operationId: getVehicleByPolicy
      tags:
        - vehicles
      parameters:
        - name: policy_number
          in: path
          required: true
          schema:
            type: string
          description: Policy number
      responses:
        '200':
          description: Vehicle found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleRecord'
        '404':
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /policies/{policy_number}:
    get:
      summary: Get policy by policy number
      description: Retrieve full policy details for workflow agent lookups
      operationId: getPolicyByNumber
      tags:
        - policies
      parameters:
        - name: policy_number
          in: path
          required: true
          schema:
            type: string
          description: Policy number (e.g., POL-2024-DE-001)
      responses:
        '200':
          description: Policy found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyRecord'
        '404':
          description: Policy not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /policies/{policy_number}/coverage/{coverage_type}:
    get:
      summary: Check if policy has specific coverage
      description: Quick check for coverage type and limit - used by Policy Checker agent
      operationId: checkPolicyCoverage
      tags:
        - policies
      parameters:
        - name: policy_number
          in: path
          required: true
          schema:
            type: string
        - name: coverage_type
          in: path
          required: true
          schema:
            type: string
          description: Coverage type to check (e.g., collision, comprehensive, liability)
      responses:
        '200':
          description: Coverage check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  has_coverage:
                    type: boolean
                  coverage_limit:
                    type: number
                    nullable: true
                  deductible:
                    type: number
        '404':
          description: Policy not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /scenarios/generate:
    post:
      summary: Generate a new demo scenario (enhanced)
      description: |
        Uses Azure OpenAI with Pydantic structured outputs to generate a 
        complete insurance claim scenario. Upon generation:
        - Policy document is indexed in FAISS (session-only)
        - Vehicle info prepared for database persistence on save
      operationId: generateScenario
      tags:
        - scenarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScenarioGenerationRequest'
      responses:
        '200':
          description: Scenario generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratedScenario'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Generation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /scenarios:
    post:
      summary: Save a generated scenario (enhanced)
      description: |
        Persist a generated scenario to the database. This now also:
        - Creates a vehicle record in the vehicles table
        - Creates a policy record in the policies table
        - Ensures policy remains indexed for workflow execution
      operationId: saveScenario
      tags:
        - scenarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveScenarioRequest'
      responses:
        '201':
          description: Scenario saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedScenarioResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    VehicleRecord:
      type: object
      required:
        - vin
        - scenario_id
        - policy_number
        - make
        - model
        - year
        - license_plate
        - created_at
      properties:
        vin:
          type: string
          minLength: 17
          maxLength: 17
          description: Vehicle Identification Number
          example: "1HGBH41JXMN109186"
        scenario_id:
          type: string
          format: uuid
          description: Associated scenario ID
        policy_number:
          type: string
          description: Associated policy number
          example: "POL-2024-DE-001"
        make:
          type: string
          description: Vehicle manufacturer
          example: "BMW"
        model:
          type: string
          description: Vehicle model
          example: "3 Series"
        year:
          type: integer
          minimum: 1900
          maximum: 2030
          description: Model year
          example: 2022
        license_plate:
          type: string
          description: License plate number
          example: "M-AB-1234"
        color:
          type: string
          nullable: true
          description: Vehicle color
          example: "Silver"
        vehicle_type:
          type: string
          nullable: true
          description: Type of vehicle
          example: "sedan"
        created_at:
          type: string
          format: date-time
          description: Record creation timestamp

    PolicyRecord:
      type: object
      description: Policy record for workflow agent lookups
      required:
        - policy_number
        - scenario_id
        - policy_type
        - coverage_types
        - coverage_limits
        - deductible
        - premium
        - effective_date
        - expiration_date
        - customer_name
        - created_at
      properties:
        policy_number:
          type: string
          example: "POL-2024-DE-001"
        scenario_id:
          type: string
          format: uuid
        policy_type:
          type: string
          enum: [basic, standard, premium, comprehensive]
        coverage_types:
          type: array
          items:
            type: string
          example: ["collision", "comprehensive", "liability", "medical"]
        coverage_limits:
          type: object
          additionalProperties:
            type: number
          example: {"collision": 50000, "liability": 100000}
        deductible:
          type: number
          example: 500
        premium:
          type: number
          example: 1200
        effective_date:
          type: string
          format: date
        expiration_date:
          type: string
          format: date
        customer_name:
          type: string
          example: "Hans Mueller"
        customer_email:
          type: string
          format: email
          nullable: true
        customer_phone:
          type: string
          nullable: true
        vin:
          type: string
          nullable: true
          description: Linked vehicle VIN
        created_at:
          type: string
          format: date-time

    ScenarioGenerationRequest:
      type: object
      properties:
        locale:
          $ref: '#/components/schemas/Locale'
        claim_type:
          $ref: '#/components/schemas/ClaimType'
        complexity:
          $ref: '#/components/schemas/Complexity'
        custom_description:
          type: string
          maxLength: 1000
          description: Optional custom scenario description
          example: "A delivery van in Rotterdam damaged two parked cars during a storm"

    GeneratedScenario:
      type: object
      required:
        - id
        - name
        - description
        - complexity
        - claim
        - policy
        - expected_outcome
        - key_points
        - workflow_tips
        - created_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          description: Descriptive scenario name
          example: "Munich Highway Collision"
        description:
          type: string
          description: Scenario description
        complexity:
          $ref: '#/components/schemas/Complexity'
        claim:
          $ref: '#/components/schemas/GeneratedClaim'
        policy:
          $ref: '#/components/schemas/GeneratedPolicy'
        expected_outcome:
          type: string
          description: Expected processing result
        key_points:
          type: array
          items:
            type: string
          description: Demonstration key points
        workflow_tips:
          type: array
          items:
            type: string
          description: Tips for presenters
        created_at:
          type: string
          format: date-time

    GeneratedClaim:
      type: object
      required:
        - description
        - damage_type
        - severity
        - estimated_amount
        - date_of_incident
        - location
        - vehicle_info
      properties:
        description:
          type: string
        damage_type:
          type: string
          example: "collision"
        severity:
          type: string
          enum: [minor, moderate, severe, total_loss]
        estimated_amount:
          type: number
          minimum: 0
        date_of_incident:
          type: string
          format: date
        location:
          type: string
        vehicle_info:
          $ref: '#/components/schemas/VehicleInfo'
        has_photos:
          type: boolean
          default: false
          description: Whether photos were submitted
        has_police_report:
          type: boolean
          default: false
          description: Whether police report was filed
        has_witness_statements:
          type: boolean
          default: false
          description: Whether witness statements exist
        weather_conditions:
          type: string
          nullable: true
        time_of_day:
          type: string
          nullable: true
        road_conditions:
          type: string
          nullable: true

    VehicleInfo:
      type: object
      required:
        - vin
        - make
        - model
        - year
        - license_plate
      properties:
        vin:
          type: string
          minLength: 17
          maxLength: 17
        make:
          type: string
        model:
          type: string
        year:
          type: integer
        license_plate:
          type: string
        color:
          type: string
          default: "Silver"
        vehicle_type:
          type: string
          default: "sedan"

    GeneratedPolicy:
      type: object
      required:
        - policy_number
        - policy_type
        - coverage_types
        - coverage_limits
        - deductible
        - premium
        - effective_date
        - expiration_date
        - customer_info
        - vehicle_info
      properties:
        policy_number:
          type: string
        policy_type:
          type: string
          enum: [basic, standard, premium, comprehensive]
        coverage_types:
          type: array
          items:
            type: string
        coverage_limits:
          type: object
          additionalProperties:
            type: number
        deductible:
          type: number
          minimum: 0
        premium:
          type: number
          minimum: 0
        effective_date:
          type: string
          format: date
        expiration_date:
          type: string
          format: date
        customer_info:
          $ref: '#/components/schemas/CustomerInfo'
        vehicle_info:
          $ref: '#/components/schemas/VehicleInfo'

    CustomerInfo:
      type: object
      required:
        - name
        - policy_number
        - email
        - phone
      properties:
        name:
          type: string
        policy_number:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string

    SaveScenarioRequest:
      type: object
      required:
        - scenario
      properties:
        scenario:
          $ref: '#/components/schemas/GeneratedScenario'
        name_override:
          type: string
          description: Optional custom name for saved scenario

    SavedScenarioResponse:
      type: object
      required:
        - id
        - name
        - created_at
        - vehicle_created
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        created_at:
          type: string
          format: date-time
        vehicle_created:
          type: boolean
          description: Whether vehicle record was successfully created

    Locale:
      type: string
      enum: [DE, NL, UK, US, FR]
      default: DE

    ClaimType:
      type: string
      enum: [auto, property, liability, theft]
      default: auto

    Complexity:
      type: string
      enum: [simple, moderate, complex]
      default: moderate

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details
